# Generated by Django 3.0.3 on 2020-02-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0003_auto_20200225_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='follow',
            new_name='following_field',
        ),
    ]
